/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.dashboard;

import com.vews.Principal;
import java.awt.BorderLayout;
import java.time.LocalDate;
import tools.UtilsGUI;

/**
 *
 * @author ldelatorrep2000
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        configComponents();
        SetDate();
        initContent();
        
        
    }
    private void initContent(){
        Principal pl = new Principal();
        pl.setSize(920,580);
        pl.setLocation(0,0);
        
        content.removeAll();
        content.add(pl,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    private void configComponents(){
        // Titulo de la ventana
        setTitle("Menu principal Zorriana");
        // posición de la ventana
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Boton_Inicio = new javax.swing.JButton();
        Boton_Cliente = new javax.swing.JButton();
        Boton_Empleados = new javax.swing.JButton();
        Boton_Proveedores = new javax.swing.JButton();
        Boton_Ventas = new javax.swing.JButton();
        Boton_Compras = new javax.swing.JButton();
        Boton_Productos = new javax.swing.JButton();
        Boton_Salida = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        Label_Dia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage( getClass().getResource("/img/icono.png")));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(642, 552));

        Menu.setBackground(new java.awt.Color(247, 139, 86));

        Boton_Inicio.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Boton_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home_Icon.png"))); // NOI18N
        Boton_Inicio.setText("INICIO");
        Boton_Inicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Inicio.setBorderPainted(false);
        Boton_Inicio.setContentAreaFilled(false);
        Boton_Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Inicio.setIconTextGap(25);
        Boton_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_InicioActionPerformed(evt);
            }
        });

        Boton_Cliente.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Boton_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Boton_Cliente.setText("CLIENTES");
        Boton_Cliente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Cliente.setBorderPainted(false);
        Boton_Cliente.setContentAreaFilled(false);
        Boton_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Cliente.setIconTextGap(25);
        Boton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ClienteActionPerformed(evt);
            }
        });

        Boton_Empleados.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Boton_Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        Boton_Empleados.setText("EMPLEADOS");
        Boton_Empleados.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Empleados.setBorderPainted(false);
        Boton_Empleados.setContentAreaFilled(false);
        Boton_Empleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Empleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Empleados.setIconTextGap(25);

        Boton_Proveedores.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Boton_Proveedores.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camion.png"))); // NOI18N
        Boton_Proveedores.setText("PROVEEDORES");
        Boton_Proveedores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Proveedores.setBorderPainted(false);
        Boton_Proveedores.setContentAreaFilled(false);
        Boton_Proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Proveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Proveedores.setIconTextGap(25);
        Boton_Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ProveedoresActionPerformed(evt);
            }
        });

        Boton_Ventas.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Boton_Ventas.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        Boton_Ventas.setText("VENTAS");
        Boton_Ventas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Ventas.setBorderPainted(false);
        Boton_Ventas.setContentAreaFilled(false);
        Boton_Ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Ventas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Ventas.setIconTextGap(25);

        Boton_Compras.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Boton_Compras.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra.png"))); // NOI18N
        Boton_Compras.setText("COMPRAS");
        Boton_Compras.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Compras.setBorderPainted(false);
        Boton_Compras.setContentAreaFilled(false);
        Boton_Compras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Compras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Compras.setIconTextGap(25);

        Boton_Productos.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Boton_Productos.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        Boton_Productos.setText("PRODUCTOS");
        Boton_Productos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Productos.setBorderPainted(false);
        Boton_Productos.setContentAreaFilled(false);
        Boton_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Productos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Productos.setIconTextGap(25);

        Boton_Salida.setFont(new java.awt.Font("Jost", 1, 24)); // NOI18N
        Boton_Salida.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        Boton_Salida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Boton_Salida.setBorderPainted(false);
        Boton_Salida.setContentAreaFilled(false);
        Boton_Salida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Salida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Salida.setIconTextGap(10);
        Boton_Salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SalidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Boton_Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Boton_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Boton_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Boton_Ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Boton_Compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Boton_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Boton_Proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(Boton_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Header.setBackground(new java.awt.Color(102, 51, 0));

        Label_Dia.setFont(new java.awt.Font("Jost", 1, 36)); // NOI18N
        Label_Dia.setForeground(new java.awt.Color(255, 255, 255));
        Label_Dia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Dia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo blanquito.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        dateText.setFont(new java.awt.Font("Jost", 1, 14)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("{dayname} {day} {month} {year}");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Dia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 604, Short.MAX_VALUE)
                .addComponent(dateText)
                .addGap(20, 20, 20))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(dateText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(Label_Dia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(0, 0));
        content.setName(""); // NOI18N
        content.setPreferredSize(new java.awt.Dimension(642, 552));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE))
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_InicioActionPerformed

    private void Boton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_ClienteActionPerformed

    private void Boton_SalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SalidaMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_SalidaMouseClicked

    private void Boton_ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_ProveedoresActionPerformed
    private void SetDate (){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero" , "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre" ,"Diciembre" ,};
        dateText.setText(dia +" "+meses [month - 1]+ " "+year);
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Cliente;
    private javax.swing.JButton Boton_Compras;
    private javax.swing.JButton Boton_Empleados;
    private javax.swing.JButton Boton_Inicio;
    private javax.swing.JButton Boton_Productos;
    private javax.swing.JButton Boton_Proveedores;
    private javax.swing.JButton Boton_Salida;
    private javax.swing.JButton Boton_Ventas;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Label_Dia;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
